name: Continuous Delivery
on:
  push:
    branches:
        - master

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
      
        - name: Simulating CD
          uses: actions/upload-artifact@v4
          with:
            name: projeto.zip
            path: |
              src/**
              public/**
              !.github
              README.md
