name: CI - ESLint exec
on:
  pull_request:
    branches: [ "master" ]

jobs:
  linting:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ESLint
        run: |
          npm install eslint@9.24.0

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
  delivery:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
      
        - name: Simulating CD
          uses: actions/upload-artifact@v4
          with:
            name: projeto.zip
            path: |
              src/**
              public/**
              !.github
              README.md
      